version: "3"

services:
  site:
    container_name: expo-odin
    command: jekyll serve --livereload --force_polling
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
